# Configuration of Hugo
title: Thiago Oliveira
baseURL: 'https://prof-thiagooliveira.netlify.app/'
canonifyURLs: true

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>

ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  post: '/post/:slug/'
  authors: '/author/:slug/'

rssLimit: 50
disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  goldmark:
    renderer:
      unsafe: true     # allow raw HTML in Markdown (for inline <style> etc.)
  highlight:
    noClasses: true    # keep Chromas' inline styles (simple, works well with HB)
    style: github      # pleasant light style; HB auto-switches for dark mode
    lineNos: false

security:
  _merge: deep

sitemap:
  _merge: deep

minify:
  disableXML: true
  tdewolff:
    html:
      keepWhitespace: false
    css:
      keepCSS2: false
    js:
      mangle: true

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: date
      weight: 10

privacy:
  youtube:
    privacyEnhanced: true
  twitter:
    enableDNT: true