# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    pageRef: /
    weight: 10

  - name: Publications
    pageRef: publication      # -> /publication/
    weight: 11

  - name: Talks
    pageRef: event            # -> /event/
    weight: 12

  # Dropdown for posts (optional)
  - name: Posts
    identifier: posts
    pageRef: post             # -> /post/
    weight: 13
  - name: All posts
    parent: posts
    pageRef: post
    weight: 14
  - name: Tags
    parent: posts
    url: /tags/               # taxonomy
    weight: 15

  - name: Experience
    pageRef: experience       # -> /experience/
    weight: 20

  - name: Projects
    pageRef: project          # -> /project/
    weight: 30

  - name: Accomplishments
    pageRef: accomplishments  # -> /accomplishments/
    weight: 40

  - name: Gallery
    pageRef: gallery          # -> /gallery/
    weight: 50
