appearance:
  mode: system
  color: blue
marketing:
  seo:
    site_type: Person
    org_name: AbacusBio
    description: Statistician—quantitative genetics, R/C++, dashboards, and reproducible
      workflows.
  analytics:
    google_analytics: G-F170NVYBW1
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
header:
  navbar:
    enable: yes
    blox: navbar
    align: center
    fixed_to_top: yes
    logo:
      text: Thiago Oliveira
      filename: logo.png
    button:
      enable: yes
      text: Contact me
      url: mailto:toliveira@abacusbio.com
    show_theme_chooser: yes
    show_search: yes
    highlight_active_link: yes
    show_translations: yes
    hide_language_name: no
footer:
  copyright:
    notice: © {year} Thiago Oliveira. This work is licensed under {license}
    license:
      enable: yes
      allow_derivatives: no
      share_alike: yes
      allow_commercial: no
locale:
  date_format: Jan 2, 2006
  time_format: 3:04 PM
  address_format: en-us
features:
  math:
    enable: yes
  privacy_pack:
    enable: yes
  map:
    provider: mapnik
    api_key: ''
    zoom: 15
custom:
  css: css/custom.css
