---
title: "Completed & Discontinued Projects"
summary: "A compilation of projects that have reached completion or were terminated." 
author: "Thiago de Paula Oliveira"
date: "`r Sys.Date()`"
type: docs
weight: 10
output:
  html_document:
    keep_md: yes
    toc: false
---

<style>
/* Blog post container */
body {
   font-family: 'Helvetica Neue', Arial, sans-serif;
   font-size: 1rem;
   line-height: 1.8;
   color: #333;
   text-align: justify;
   background-color: #fafafa;
   margin: 0;
   padding: 0 20px;
}

/* Header styling */
h1, 
h2, 
h3, 
h4, 
h5, 
h6 {
  font-weight: 600; /* Semi-bold for a professional look */
  margin-bottom: 0.75em; /* Slightly reduced bottom margin */
  color: #0d0d0d;
  line-height: 1.2;
  margin-top: 1.5em; /* Added top margin for consistency */
}

h1 {
  font-size: 1.75rem; 
  border-bottom: 2px solid #3b80d1;
  padding-bottom: 0.3em; /* Padding for visual separation */
  margin-top: 1em; 
}

h2 {
  font-size: 1.5rem; 
  color: #3b80d1;
  padding-bottom: 0.2em; /* Padding for visual separation */
}

h3 {
  font-size: 1.25rem; 
  color: #333;
}

h4 {
  font-size: 1.125rem; 
  color: #333;
}

h5 {
  font-size: 1rem; 
  color: #333;
}

h6 {
  font-size: 0.875rem; 
  color: #333;
}

/* Link styling */
a {
  color: #3b80d0;
  text-decoration: none;
  transition: color 0.3s ease;
}

a:hover {
  text-decoration: underline;
  color: #1a57a0;
}

/* Code styling */
pre, 
.code-input {
  background-color: #f5f5f5;
  border: 1px solid #ddd;
  padding: 10px;
  font-size: 0.9rem;
  border-radius: 5px;
  margin: 20px 0;
  overflow-x: auto;
}

code {
  font-size: 0.9rem;
  background-color: #f5f5f5;
  padding: 2px 4px;
  border-radius: 3px;
}

/* Table styling */
table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 1.5em;
  text-align: left;
}

th, 
td {
  padding: 12px;
  border: 1px solid #ddd;
}

th {
  background-color: #3b80d1;
  color: white;
}

/* Div options - color box text */
.div-1 {
  color: black;
  background-color: #d6edd3;
  padding: 10px;
  border-radius: 5px;
  margin-bottom: 1.5em;
}

.div-2 {
  color: black;
  background-color: #cfbe7e;
  padding: 10px;
  border-radius: 5px;
  margin-bottom: 1.5em;
}

/* Article content */
.article-content {
  text-align: justify;
}

/* Image styling */
img {
  max-width: 100%;
  height: auto;
  border-radius: 5px;
  margin-bottom: 1.5em;
}
</style>

```{r setup, include=FALSE}
# Configuring global parameters
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error=FALSE, warning = FALSE,
                      fig.align = "center", fig.height = 6, fig.width = 6,
                      class.source = "lineAnchors")
```

## 2024

### Quantifying the drivers of genetic change in plant breeding

**Summary**:
Plant breeding programmes are a complex network of a multitude of operations and decisions. Therefore quantifying which operations and decisions drive genetic change in plant breeding is challenging. Traditionally we measure the genetic change with a phenotypic or genetic trend, but these trends measure only change in the mean. To understand genetic change and its drivers more comprehensively, we also need to measure changes in genetic mean and variance and evaluate drivers of changes in mean and variance.

<br>

<hr>

## 2023

### Developing high performance black soldier fly breeds for insects-as-feed sector

**Summary**: 
The rising demand for livestock and aquaculture protein necessitates sustainable alternatives to soy and fishmeal, with the black soldier fly emerging as a key solution. This project aims to develop a breeding program and tools to enhance the genetics and production efficiency of black soldier fly, supporting the growing number of global producers.

<br>

### A hierarchical approach for evaluating athlete performance  

**Summary**: 
The hierarchical approach for evaluating athlete performance utilizes mixed-effects regression models and principal component analysis to create the ON score, a comprehensive metric that captures an athlete’s overall contribution to their team. This method, validated on NBA data, offers a reliable and efficient tool for coaches and managers to assess and compare athlete performance across seasons and games, enhancing decision-making in sports analytics by providing deeper insights into individual and team dynamics.


**Publications**:

1. [A hierarchical approach for evaluating athlete performance with an application in elite basketball](https://www.nature.com/articles/s41598-024-51232-2)

<br>

### A comparative study of markerless and marker-based systems

**Summary**: 
This project aims to evaluate the agreement between markerless and marker-based motion capture systems using 95% functional limits of agreement within a linear mixed-effects modeling framework. By comparing these systems, the study seeks to determine the reliability and applicability of markerless technology in biomechanical analysis, which could significantly streamline data collection and reduce setup time while maintaining accuracy. This research will provide valuable insights for improving motion capture methods used in sports and clinical biomechanics.

**Publications**:

1. [Comparison of markerless and marker-based motion capture systems using 95% functional limits of agreement in a linear mixed-effects modelling framework](https://www.nature.com/articles/s41598-023-49360-2)

<br>

<hr>

## 2022

### AlphaPart - Partition of Breeding Values by Paths of Information

**Summary**: 
The partitioning method is described in Garcia-Cortes et al. (2008). The package includes the main function AlphaPart for partitioning breeding values and auxiliary functions for manipulating data and summarizing, visualizing, and saving results.

**Publications**:

1. [A method for partitioning trends in genetic mean and variance to understand breeding practices](https://doi.org/10.1186/s12711-023-00804-3)

**R Package**:

1. [AlphaPart: Partition/Decomposition of Breeding Values by Paths of Information](https://CRAN.R-project.org/package=AlphaPart)

<br>

### Genomic strategies for optimal crossbreeding in African dairy cattle

**Summary**: 
Develop genomic strategies to optimise crossbreeding in livestock breeding programmes with focus on East African crossbred dairy cattle

<br>

<hr>

## 2021

### The use of biostatistics for optimizing athletes performance

**Summary**: 
Uniquely blending Data Science and Sports Science to generate customized strategies by athlete

**Publications**:

1. [Modelling menstrual cycle length in athletes using state-space models, 2021](https://www.nature.com/articles/s41598-021-95960-1)

<br>

### Development of predictive models and analytics techniques to forecast historical data-driven outcomes

**Summary**: 
Predictive modelling is a commonly used statistical technique to predict future behavior. Predictive modelling solutions are a form of data-mining technology that analyses historical and current data and generates a model to help predict future outcomes. In predictive modelling, data is collected, a statistical model is formulated, predictions are made, and the model is validated as additional data becomes available.

**Publications**:

1. [Global short-term forecasting of COVID-19 cases, 2021](https://www.nature.com/articles/s41598-021-87230-x)
2. [Modelling menstrual cycle length in athletes using state-space models, 2021](https://www.nature.com/articles/s41598-021-95960-1)

<br>

### Optimising selection and management of diversity in plant breeding

**Summary**: 
This project aims to quantify and manage genetic variation in plant breeding programs, ensuring long-term competitiveness by measuring and distributing genetic diversity across different stages and years.

**Publications**: 

1. [Temporal and genomic analysis of additive genetic variance in breeding programmes](https://www.nature.com/articles/s41437-021-00485-y)

<br>

<hr>

## 2020

### The lcc Package

**Summary**: 
Longitudinal concordance correlation (LCC) is a statistical measure used to assess the agreement between two methods of measurement over time. It combines aspects of precision and accuracy to evaluate the consistency and accuracy of longitudinal data, accounting for both within-subject correlation and temporal changes. LCC is particularly useful in fields where repeated measurements are essential, such as medical research, to ensure that methods produce reliable and consistent results across different time points.

**Publications**:

1. [lcc: Longitudinal Concordance Correlation, 2019](https://cran.r-project.org/web/packages/lcc/lcc.pdf)
2. [lcc: an R package to estimate the concordance correlation, Pearson correlation and accuracy over time, 2020](https://peerj.com/articles/9850/)

**R Package**:

1. [lcc: Longitudinal Concordance Correlation](https://CRAN.R-project.org/package=lcc)

<br>

### Transmission efficiency of *xylella fastidiosa*

**Summary**:
*Xylella fastidiosa* is genetically diverse and has many vector species. However, there is limited information on vector specificity and efficiency for different sequence types (STs) Both STs of X. fastidiosa and vectors differ in their associations with plants

**Publications**:

1. [Transmission efficiency of xylella fastidiosa subsp. Pauca sequence types by sharpshooter vectors after in vitro acquisition, 2018](https://apsjournals.apsnet.org/doi/pdf/10.1094/PHYTO-07-18-0254-FI)
2. [Settling and feeding behavior of sharpshooter vectors on plum genotypes with different susceptibility levels to leaf scald disease (Xylella fastidiosa), 2020](https://link.springer.com/article/10.1007%2Fs10658-020-02104-8)

<br>
<hr>

## 2019

### Sugarcane straw management for bioenergy

**Summary**:
Global warming can intensify the soil organic matter (SOM) turnover, damaging soil health. Crop residues left on the soil are important to maintain a positive SOM budget and nutrient cycling. But, sugarcane (Saccharum officinarum) straw has been removed from the field for bioenergy purposes. We hypothesize that global warming, together with straw removal, will negatively impact Brazil’s ethanol carbon footprint.

**Publications**:

1. [Sugarcane straw management for bioenergy: effects of global warming on greenhouse gas emissions and soil carbon storage](https://link.springer.com/article/10.1007/s11027-019-09880-7)

<br>

### Measuring color using image analysis

**Summary**: 
Promote the usage of image analysis as well as development of statistical methodologies for that purpose.

**Publications**:

1. [Measuring color hue in 'Sunrise Solo' papaya using a flatbed scanner (2017)](https://www.scielo.br/j/rbf/a/X6xRm34btCXNMJYGdxzdcKB/?format=pdf&lang=en)
2. [Longitudinal concordance correlation function based on variance components: an application in fruit color analysis, 2018](https://link.springer.com/article/10.1007%2Fs13253-018-0321-1)

    
